---
pkgs:
  - adwaita-icon-theme
  - alsa-utils
  - arandr
  - aspell
  - compton
  - emojione-color-font-ttf
  - en-hunspell
  - espeak
  - feh
  - firefox
  - gnome-icons-elementary
  - gtk-murrine-engine
  - hicolor-icon-theme
  - higan
  - hunspell
  - i3
  - i3lock
  - keepassxc
  - lxappearance
  - mate-notification-daemon
  - mupdf
  - numix-theme
  - pavucontrol
  - pcmanfm
  - redshift
  - rofi
  - rxvt-unicode
  - scrot
  - vlc
  - webcamd
  - wpa_gui
  - xautolock
  - xbacklight
  - xclip
  - xev
  - xf86-video-intel
  - xinit
  - xinput
  - xkbcomp
  - xkill
  - xmodmap
  - xorg
  - xorg-server
  - xprop
  - xrandr
  - xrdb
  - xrefresh
  - xset
  - zathura
  - zathura-pdf-mupdf
  - zim
